language: ruby
cache: bundler
git:
    submodules: true
script:
  - ./generate.sh
deploy:
  local-dir: gen
  repo: passepartoutvpn/api
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
      branch: master #push-to-github
  target-branch: master #example
